### 회원등록
POST http://localhost:8080/api/v2/members
Content-Type: application/json

{
  "name": "hello3"
}

### 회원 수정
PUT http://localhost:8080/api/v2/members/1
Content-Type: application/json

{
  "name": "new-hello"
}

### 회원조회
GET http://localhost:8080/api/v2/members
Content-Type: application/json

### 간단한 주문조회
GET http://localhost:8080/api/v3/simple-orders
Content-Type: application/json

### 주문조회v3.1
GET http://localhost:8080/api/v3.1/orders?offset=0&limit=100
Content-Type: application/json

### 주문조회v4
GET http://localhost:8080/api/v4/orders
Content-Type: application/json
